In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [ ]:
scalar = torch.tensor(7)
scalar
# print(type(scalar))

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item() #getting scalar back as python int

7

In [ ]:
vector = torch.tensor([7,7])
vector
# print(type(vector))

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3,4],[3,6,7,7],[6,7,8,9]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [3, 6, 7, 7],
         [6, 7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 4])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3, 4],
        [3, 6, 7, 7],
        [6, 7, 8, 9]])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3, 4],
        [3, 6, 7, 7],
        [6, 7, 8, 9]])

In [ ]:
# random  tensors
random_tensor = torch.rand(2,4)
random_tensor

tensor([[0.4579, 0.1240, 0.8123, 0.8026],
        [0.6646, 0.1551, 0.4923, 0.5519]])

In [ ]:
random_tensor = torch.rand(3,10,10)
random_tensor

tensor([[[0.8711, 0.8341, 0.3252, 0.6131, 0.6589, 0.4531, 0.0486, 0.9062,
          0.4909, 0.5676],
         [0.1007, 0.5717, 0.8105, 0.1325, 0.9958, 0.6423, 0.6521, 0.8343,
          0.4551, 0.5682],
         [0.1125, 0.3900, 0.0086, 0.6928, 0.6682, 0.1805, 0.5666, 0.4929,
          0.2425, 0.0203],
         [0.6876, 0.5462, 0.1086, 0.8718, 0.7564, 0.0030, 0.3746, 0.7974,
          0.8156, 0.9049],
         [0.4015, 0.0826, 0.7236, 0.9498, 0.3754, 0.5777, 0.5190, 0.7270,
          0.6580, 0.6105],
         [0.7965, 0.5337, 0.4043, 0.0063, 0.0973, 0.3481, 0.8814, 0.8549,
          0.0775, 0.7769],
         [0.6226, 0.6555, 0.4563, 0.0602, 0.2398, 0.2209, 0.0265, 0.9684,
          0.1240, 0.6129],
         [0.0147, 0.6414, 0.7115, 0.4668, 0.3573, 0.2649, 0.3043, 0.5981,
          0.0755, 0.7438],
         [0.1370, 0.1847, 0.3648, 0.0889, 0.2364, 0.6407, 0.1174, 0.7006,
          0.7885, 0.0372],
         [0.1531, 0.7383, 0.2187, 0.1738, 0.3278, 0.6657, 0.4234, 0.3905,
          0.8742,

In [ ]:
random_tensor.ndim

3

In [ ]:
#creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,widht,colorchannel(r,g,b)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zero = torch.zeros(size=(3,10,10))
zero

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.,

In [ ]:
zero * random_tensor

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.,

In [ ]:
one = torch.ones(size=(3,10,10))
one

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.,

In [ ]:
one * random_tensor

tensor([[[0.8711, 0.8341, 0.3252, 0.6131, 0.6589, 0.4531, 0.0486, 0.9062,
          0.4909, 0.5676],
         [0.1007, 0.5717, 0.8105, 0.1325, 0.9958, 0.6423, 0.6521, 0.8343,
          0.4551, 0.5682],
         [0.1125, 0.3900, 0.0086, 0.6928, 0.6682, 0.1805, 0.5666, 0.4929,
          0.2425, 0.0203],
         [0.6876, 0.5462, 0.1086, 0.8718, 0.7564, 0.0030, 0.3746, 0.7974,
          0.8156, 0.9049],
         [0.4015, 0.0826, 0.7236, 0.9498, 0.3754, 0.5777, 0.5190, 0.7270,
          0.6580, 0.6105],
         [0.7965, 0.5337, 0.4043, 0.0063, 0.0973, 0.3481, 0.8814, 0.8549,
          0.0775, 0.7769],
         [0.6226, 0.6555, 0.4563, 0.0602, 0.2398, 0.2209, 0.0265, 0.9684,
          0.1240, 0.6129],
         [0.0147, 0.6414, 0.7115, 0.4668, 0.3573, 0.2649, 0.3043, 0.5981,
          0.0755, 0.7438],
         [0.1370, 0.1847, 0.3648, 0.0889, 0.2364, 0.6407, 0.1174, 0.7006,
          0.7885, 0.0372],
         [0.1531, 0.7383, 0.2187, 0.1738, 0.3278, 0.6657, 0.4234, 0.3905,
          0.8742,

In [ ]:
#range of tensors
torch.range(0,10) #range is going to be deprecated

<ipython-input-26-6d8ae4469e9c>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10) #range is going to be deprecated


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(5,50,4)

tensor([ 5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [ ]:
torch.arange(end=500,start=50,step=14)

tensor([ 50,  64,  78,  92, 106, 120, 134, 148, 162, 176, 190, 204, 218, 232,
        246, 260, 274, 288, 302, 316, 330, 344, 358, 372, 386, 400, 414, 428,
        442, 456, 470, 484, 498])

In [ ]:
fifty_to_fiveh =torch.arange(end=500,start=50,step=14)

In [ ]:
#tensor like creating a tensor to similar tensor already defined
ten_zeros = torch.zeros_like(input=fifty_to_fiveh)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0])

#tensor data types

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0])
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_int = torch.tensor([3,6,9])
float_32_int


tensor([3, 6, 9])

In [ ]:
float_32_int.dtype

torch.int64

by default, for decimal in tensor the default datatype is float 32 and for integer it is int64

In [ ]:
float_16_tensor = torch.tensor([3.0,6.0],dtype=torch.
float16)
float_16_tensor.dtype
#by default the data type is 32 and we can specify the datatype to be used in arguments

torch.float16

In [ ]:
float_16_tensor = torch.tensor([3.0,6.0],dtype=None,device=None,requires_grad=False)
float_16_tensor.dtype

torch.float32

In [ ]:
# to convert a tensor datatype into another
float_16_tensor1 = float_32_tensor.type(torch.half)  #its same as float 16
float_16_tensor1

tensor([3., 6., 9.], dtype=torch.float16)

tensor operations - add, sub, mult(normal element wise), div, matrix mul(dot product)

In [ ]:
new_tensor = torch.tensor([3,6,9])
print(new_tensor)
new_tensor + 100


tensor([3, 6, 9])


tensor([103, 106, 109])

In [ ]:
print(new_tensor) # so performing operations doesn't change the original tensor so you might have to assign it
# to a new variable

tensor([3, 6, 9])


In [ ]:
#built in functions
torch.mul(new_tensor,10)

tensor([30, 60, 90])

In [ ]:
torch.add(new_tensor,50)

tensor([53, 56, 59])

In [ ]:
#element wise multiplication

print(new_tensor , "*", new_tensor)
print(f"Equals: {new_tensor * new_tensor} ")

tensor([3, 6, 9]) * tensor([3, 6, 9])
Equals: tensor([ 9, 36, 81]) 


In [ ]:
# matrix multiplication
torch.matmul(new_tensor,new_tensor)

tensor(126)

builtin methods use much less time when performing operations

In [ ]:
%%time
value = 0
for i in range(len(new_tensor)):
  value += new_tensor[i] * new_tensor[i]
print(value)

tensor(126)
CPU times: user 1.51 ms, sys: 0 ns, total: 1.51 ms
Wall time: 1.53 ms


In [ ]:
%%time
torch.matmul(new_tensor,new_tensor)

CPU times: user 105 µs, sys: 0 ns, total: 105 µs
Wall time: 158 µs


tensor(126)

In [ ]:
#shape errors

tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

tensor_B = torch.tensor([[7,10],[8,11],[1,6]])
print(tensor_A.shape,tensor_B.shape)
torch.mm(tensor_A,tensor_B)

torch.Size([3, 2]) torch.Size([3, 2])


RuntimeError: ignored

In [ ]:
 #fixing shape errors

 tensor_B.T, tensor_B
 tensor_B.shape
 tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
print(torch.mm(tensor_A,tensor_B.T))
print(torch.mm(tensor_A,tensor_B.T).shape)
print(tensor_A.shape,tensor_B.shape)

tensor([[ 27,  30,  13],
        [ 61,  68,  27],
        [ 95, 106,  41]])
torch.Size([3, 3])
torch.Size([3, 2]) torch.Size([3, 2])


In [ ]:
#finding min,max,mean,sum etc(tensor aggregation)

x = torch.arange(0,100,10)
x
x.dtype

torch.int64

In [ ]:
torch.min(x)
x.min()

tensor(0)

In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
#finding the positional min and max

x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin() #find the position(index) of minimum of tensor

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

In [ ]:
#reshaping, stacking, squeezing, unsqueezing
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add extra dimesion
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape,x #changes made in reshape is not reflected in x

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_reshaped = x.reshape(3,2)
x_reshaped, x_reshaped.shape

RuntimeError: ignored

In [ ]:
#change view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#change view
z = x.view(9,1)
z,z.shape

#changing z changes x (view of a tensor shares the same memory as the original input)

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
z[ 0] = 5
z,x #changes in z made the changes in x as seen below

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
 #stack
 x_stacked = torch.stack([x,x,x,x,x],dim =0)
 x_stacked,x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
 #stack
 x_stacked = torch.stack([x,x,x,x,x],dim =1)
 x_stacked,x

(tensor([[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.],
         [5., 5., 5., 5., 5.],
         [6., 6., 6., 6., 6.],
         [7., 7., 7., 7., 7.],
         [8., 8., 8., 8., 8.],
         [9., 9., 9., 9., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#squeeze - removes single dimension from all tensors
x_reshaped.shape

torch.Size([9, 1])

In [ ]:
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x_reshaped.squeeze(),x_reshaped.squeeze().shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped_squeezed = x_reshaped.squeeze()
x_reshaped_squeezed

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped_squeezed.unsqueeze(dim=0),x_reshaped_squeezed.unsqueeze(dim=0).shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped_squeezed.unsqueeze(dim=1),x_reshaped_squeezed.unsqueeze(dim=1).shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#permute          most used with image data
x_original = torch.rand(size=(224,224,3))

x_original


tensor([[[0.2964, 0.9188, 0.3526],
         [0.2729, 0.2344, 0.5967],
         [0.0307, 0.0925, 0.1697],
         ...,
         [0.9159, 0.6256, 0.9797],
         [0.5229, 0.6434, 0.5215],
         [0.5458, 0.3866, 0.5081]],

        [[0.9813, 0.4597, 0.3243],
         [0.9447, 0.4405, 0.1287],
         [0.2380, 0.9788, 0.9724],
         ...,
         [0.0865, 0.6846, 0.0880],
         [0.8300, 0.4479, 0.7958],
         [0.2574, 0.1090, 0.3494]],

        [[0.6362, 0.0444, 0.9243],
         [0.3962, 0.3914, 0.6184],
         [0.9187, 0.9129, 0.4284],
         ...,
         [0.6772, 0.8058, 0.2182],
         [0.6366, 0.8442, 0.4912],
         [0.0619, 0.2651, 0.2396]],

        ...,

        [[0.4045, 0.3324, 0.7084],
         [0.4121, 0.3869, 0.9352],
         [0.9256, 0.9843, 0.2334],
         ...,
         [0.6872, 0.5890, 0.6625],
         [0.8620, 0.8172, 0.1121],
         [0.2213, 0.3219, 0.0577]],

        [[0.4094, 0.6924, 0.3956],
         [0.9584, 0.9652, 0.0816],
         [0.

In [ ]:
x_permuted = x_original.permute(2,0,1)
x_permuted

tensor([[[0.2964, 0.2729, 0.0307,  ..., 0.9159, 0.5229, 0.5458],
         [0.9813, 0.9447, 0.2380,  ..., 0.0865, 0.8300, 0.2574],
         [0.6362, 0.3962, 0.9187,  ..., 0.6772, 0.6366, 0.0619],
         ...,
         [0.4045, 0.4121, 0.9256,  ..., 0.6872, 0.8620, 0.2213],
         [0.4094, 0.9584, 0.8472,  ..., 0.1299, 0.3588, 0.7110],
         [0.9886, 0.2700, 0.2460,  ..., 0.8486, 0.3827, 0.4878]],

        [[0.9188, 0.2344, 0.0925,  ..., 0.6256, 0.6434, 0.3866],
         [0.4597, 0.4405, 0.9788,  ..., 0.6846, 0.4479, 0.1090],
         [0.0444, 0.3914, 0.9129,  ..., 0.8058, 0.8442, 0.2651],
         ...,
         [0.3324, 0.3869, 0.9843,  ..., 0.5890, 0.8172, 0.3219],
         [0.6924, 0.9652, 0.0969,  ..., 0.4311, 0.9106, 0.9683],
         [0.5908, 0.7940, 0.6979,  ..., 0.9159, 0.9940, 0.5616]],

        [[0.3526, 0.5967, 0.1697,  ..., 0.9797, 0.5215, 0.5081],
         [0.3243, 0.1287, 0.9724,  ..., 0.0880, 0.7958, 0.3494],
         [0.9243, 0.6184, 0.4284,  ..., 0.2182, 0.4912, 0.

In [ ]:
x_original.shape,x_permuted.shape  #view has changed, permuted uses same memory as original like view

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
print(array.dtype)
tensor = torch.from_numpy(array)
array,tensor

float64


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#numpy default datatype is float64 and torch is float 32

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
array = array +1
array,tensor           #changing array doesn't change tensor by default, we have to change it every time

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to numpy
tensor = torch.ones(7)
print(tensor)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor


tensor([1., 1., 1., 1., 1., 1., 1.])


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype #orginal datatype will remain even after converting

dtype('float32')

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#reproducibility (taking random out of random)
torch.rand(3,3)



tensor([[0.4213, 0.5777, 0.6606],
        [0.6743, 0.6847, 0.5628],
        [0.1171, 0.7167, 0.3016]])

In [ ]:
random_tensorA = torch.rand(3,4)
random_tensorB = torch.rand(3,4)
print(random_tensorA,random_tensorB)
print(random_tensorA == random_tensorB)

tensor([[0.2182, 0.0080, 0.6318, 0.8539],
        [0.3695, 0.2666, 0.5886, 0.3726],
        [0.5589, 0.1209, 0.0591, 0.3431]]) tensor([[0.2806, 0.9679, 0.7476, 0.3218],
        [0.2279, 0.2119, 0.3303, 0.2169],
        [0.5005, 0.5225, 0.0687, 0.0816]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensorC = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensorD = torch.rand(3,4)
print(random_tensorC, random_tensorD)
print(random_tensorC == random_tensorD)

# sometimes we are in hurry to create multiple tensor with same random numbers then we can use this
# making random numbers reproducible

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi

Mon Sep  4 09:49:33 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
#setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
# count no of gpu
torch.cuda.device_count()

1

In [ ]:
# putting tensors on gpu


tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor = torch.tensor([1,2,3])
print(tensor)

tensor([1, 2, 3])


In [ ]:
# moving tensor to gpu
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)
#device agnostic code makes it easier to move, if cuda not available then it will run on cpu
# if there is no device agnostic code it might genearte error
# cuda:0 tells us that there is only one gpu and it's running on that, if there are more then it will show otherwise

tensor([1, 2, 3], device='cuda:0')


In [ ]:
#if tensor on gpu, then can't transform to numpy because numpy doesn't work on gpu
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
#to fix the issue
tensor_backon_cpu = tensor_on_gpu.cpu().numpy()
tensor_backon_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')